nodeLinker: node-modules

npmRegistryServer: "https://nexus.kontur.host/repository/kontur-npm-group/"

npmPublishRegistry: "https://registry.npmjs.org"

npmScopes:
  skbkontur:
    npmPublishRegistry: "https://registry.npmjs.org"
    npmAuthToken: "${YARN_NPM_AUTH_TOKEN-}"

defaultSemverRangePrefix: ""

cacheFolder: .yarn-cache