export enum MarkdownFormat {
  h2 = 'h2',
  h3 = 'h3',
  h4 = 'h4',
  bold = 'bold',
  italic = 'italic',
  crossed = 'crossed',
  ref = 'ref',
  quote = 'quote',
  codeBlock = 'codeBlock',
  code = 'code',
  list = 'list',
  checkedList = 'checkedList',
  numberedList = 'numberedList',
  table = 'table',
  file = 'file',
  image = 'image',
}
