export enum MarkdownTids {
  HeadingDropdown = 'MarkdownHeadingDropdown',
  HeadingH2 = 'MarkdownHeadingH2',
  HeadingH3 = 'MarkdownHeadingH3',
  HeadingH4 = 'MarkdownHeadingH4',
  Bold = 'MarkdownBold',
  Italic = 'MarkdownItalic',
  Crossed = 'MarkdownCrossed',
  Ref = 'MarkdownRef',
  List = 'MarkdownList',
  CheckedList = 'MarkdownCheckedList',
  NumberedList = 'MarkdownNumberedList',
  CodeBlock = 'MarkdownCodeBlock',
  Quote = 'MarkdownQuote',
  Table = 'MarkdownTable',
  AttachFile = 'MarkdownAttachFile',
  Emoji = 'MarkdownEmoji',
  AI = 'MarkdownAI',
  Help = 'MarkdownHelp',
  SplitView = 'MarkdownSplitView',
  EditView = 'MarkdownEditView',
  PreviewView = 'MarkdownPreviewView',
  FullscreenToggle = 'MarkdownFullscreenToggle',
}
